INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Fast food');
INSERT INTO unit_of_measurement (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measurement (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measurement (description) VALUES ('Cup');
INSERT INTO unit_of_measurement (description) VALUES ('Pinch');
INSERT INTO unit_of_measurement (description) VALUES ('Ounce');
INSERT INTO unit_of_measurement (description) VALUES ('Each');
INSERT INTO unit_of_measurement (description) VALUES ('Dash');
INSERT INTO unit_of_measurement (description) VALUES ('Pint');